[package]
name = "germ-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
constcat.workspace = true
either.workspace = true
futures-util.workspace = true
fxhash.workspace = true
log.workspace = true
md-5.workspace = true
nix.workspace = true
rayon.workspace = true
redb.workspace = true
fancy-regex.workspace = true
rkyv.workspace = true
rust-ini.workspace = true
shlex.workspace = true
thiserror.workspace = true
tokio.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
